### ISSUE TITLE
Not recognized by Steam

### ISSUE THREAD

**Issue by Pakrohk** [pythonlover02/Proton-Sarek#1]
I installed the latest async version, i.e. 9.15, unfortunately, it is not displayed in Steam at all (I put porotonge in the same folder, but it is available for selection in Steam)

**Comment by klinux86** [comment]
> I installed the latest async version, i.e. 9.15, unfortunately, it is not displayed in Steam at all (I put porotonge in the same folder, but it is available for selection in Steam)

Add proton- to the name of the folder

**Comment by pythonlover02** [comment]
> I installed the latest async version, i.e. 9.15, unfortunately, it is not displayed in Steam at all (I put porotonge in the same folder, but it is available for selection in Steam)

That's strange, to say the least. Could you let me know which Linux distribution you're using and whether you're using the Steam version from your distro's package manager, the one from the Steam website, or the Flatpak version? I'd like to investigate the issue and see if it's specific to a particular distro or package.

**Comment by pythonlover02** [comment]
> Add proton- to the name of the folder

Thanks for the help [klinux86](https://github.com/klinux86)

**Comment by Pakrohk** [comment]
> > I installed the latest async version, i.e. 9.15, unfortunately, it is not displayed in Steam at all (I put porotonge in the same folder, but it is available for selection in Steam)
> 
> That's strange, to say the least. Could you let me know which Linux distribution you're using and whether you're using the Steam version from your distro's package manager, the one from the Steam website, or the Flatpak version? I'd like to investigate the issue and see if it's specific to a particular distro or package.

Distro: Arch
Desktop : Plasma 
Steam : multilib/steam

**Comment by klinux86** [comment]
> > Add proton- to the name of the folder
> 
> Thanks for the help [klinux86](https://github.com/klinux86)

I should instead thank you for the great work that you did, in fact I'm using the same config as Pakrohk

**Comment by pythonlover02** [comment]
> I should instead thank you for the great work that you did, in fact I'm using the same config as Pakrohk

Your welcome *:)*, its an honor than my custom builds are being used. 
Now about the problem; Does Proton-Sarek[version] works too or only proton-Sarek[version]? 
Once you answer me, I’ll be on my way to change the name of the builds from the 9-13 release to the 9-15 release. I really don’t want any users to have to use workarounds to make it work.

**Comment by klinux86** [comment]
> > I should instead thank you for the great work that you did, in fact I'm using the same config as Pakrohk
> 
> Your welcome _:)_, its an honor than my custom builds are being used. Now about the problem; Does Proton-Sarek[version] works too or only proton-Sarek[version]? Once you answer me, I’ll be on my way to change the name of the builds from the 9-13 release to the 9-15 release. I really don’t want any users to have to use workarounds to make it work.

I confirm that upper case is working also and showing on steam "GE-PROTON9-15", I suggest that you change the name showed to "GE-PROTON9-15-SAREK" in order to distinguish if we are using regular GE-PROTON, thx in advance.

**Comment by pythonlover02** [comment]
> I confirm that upper case is working also and showing on steam "GE-PROTON9-15", I suggest that you change the name showed to "GE-PROTON9-15-SAREK" in order to distinguish if we are using regular GE-PROTON, thx in advance.

Thats good to know, about the name GE-PROTON9-15-SAREK its way to long, i was testing it on my secondary pc that uses a 1024x768 monitor and it occupied 3 lines to display the full name on the Proton selection, so for now i will rename it to Proton-Sarek9-15. Also, thanks for your help *:)*

**Comment by pythonlover02** [comment]
Nevermind the problem was on compatibilitytool.vdf file, i forgot to update it on the 9-15 release, it had been fixed now
