### ISSUE TITLE
Latest Release (9-20) not working on my end

### ISSUE THREAD

**Issue by joaomiguel-sb** [pythonlover02/Proton-Sarek#10]
I couldn't launch any game on the newest release no matter what commands i tried using, and launching steam through the terminal didn't show me anything meaningful, I also wasn't able to get anything from the PROTON_LOG command, as the games crashed before even booting, so I downgraded to 9-18 and it worked right out of the box.
No idea why though.

Specs:
Distro: Manjaro XFCE
GPU: GT740M
CPU: i7-3537U

If you want any more information or testing, ask away

As an addendum:
The 9-19 release also works fine, and I don't know if this is intended behavior or not, but using Sarek makes it so that my games don't load their cloud saves, and create their own that only loads when using either Sarek or Async Sarek, and these two create save files independent from one another too.

**Comment by pythonlover02** [comment]
I have thoroughly checked the `proton`, `wine.inf`, `user.reg` files, and the `dxvk` ones to ensure they were correctly overwritten. Everything appears to be in order. The only difference between Sarek9-20 and Sarek9-19 is a small hotfix introduced in Proton-GE9-20, as you can see in this [commit](https://github.com/pythonlover02/Proton-Sarek/commit/3e08416afa4c059cbfd3e3b79bf2e1269a48ce57). This makes the issue even more strange, given that the 9-19 release works fine.

> **Note:** Using Sarek causes my games not to load their cloud saves and creates independent save files for Sarek and Async Sarek.

This behavior is not intended at all. Once we get the 9-20 release on your PC, I will look into this further.

Here are some questions to help diagnose this strange issue:

1. **Did you install it manually or using ProtonPlus?**
2. **Are you using Flatpak Steam or the native version?**

These details will help us gather more information about the issue. And thanks for reporting this :).

**Comment by joaomiguel-sb** [comment]
No problem!
As for your questions:
1. I installed Proton-Sarek manually
2. I'm using native Steam

**Comment by pythonlover02** [comment]
To ensure there are no issues with the extraction of the 9-20 release, please remove the 9-20 release files from your directory. Next, reinstall the 9-20 release through ProtonPlus. After completing the installation, restart Steam to apply the changes. Once Steam has restarted, attempt to launch your game again. This process its to see if there are any extraction related problems with the release.
I will be checking the Sarek-Patches files, to see if i missed anything

**Comment by joaomiguel-sb** [comment]
Installed both 9-20 and 9-20-async through ProtonPlus and got the same result. :/

**Comment by pythonlover02** [comment]
> Installed both 9-20 and 9-20-async through ProtonPlus and got the same result. :/

Found the error, a new build should be out in some hours

**Comment by pythonlover02** [comment]
Check if the [9-20-r1](https://github.com/pythonlover02/Proton-Sarek/releases/tag/Sarek9-20-r1) release works.

**Comment by joaomiguel-sb** [comment]
Yes! It works just fine now, only the save issue persists, though now both the regular and async versions of Proton-Sarek seem to be sharing the same save file, which still isn't the one on Steam Cloud
