### ISSUE TITLE
Blood Strike (NetEase) run in Proton-Sarek, but not use my iGPU (Intel HD Graphics), (Use in GPU 0%)

### ISSUE THREAD

**Issue by Pallas13** [pythonlover02/Proton-Sarek#18]
Hello, your project is very good, I use Latest of Proton Sarek to run Blood Strike in Lutris, with DXVK 1.10.3 or DXVK Sarek but by some motive. The CPU run in 100% and GPU is 0%, but use PREFIX Default of Lutris (Wine GE), have used of GPU, with "smail" use of CPU in comparison with Sarek ≃ 90%/100% and used of GPU is variable ≃ 60%.

A fact, using a command for viewer GPU use by process, (nvtop). Using Proton Sarek, the GPU is used, but no is high (Type 90% or 60%), is ≃ 09%/34%. 

System Information:
Operating System: BigLinux based in Manjaro Linux 
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.1
Kernel Version: 6.6.65-x64v1-xanmod1-1-lts (64-bit)
Graphics Platform: Wayland
Processors: 2 × Intel® Celeron® CPU N3060 @ 1.60GHz
Memory: 3.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 400
Manufacturer: LENOVO
Product Name: 80W2
System Version: Lenovo ideapad 110-15IBR

Vulkan Version: 1.2.289

**Comment by pythonlover02** [comment]
Hi there, first of all are you using Gamemode?

I ask this because Proton-Sarek(and any Proton version rn) cannot currently load the gamemode binaries, this is because the Steam update that added the screen capture option messed up Proton performance, so Valve set the LD_PRELOAD to "", meaning it will not load for example the gamemode binaries. 
However, I am currently working on code that will look for the gamemode binaries and use them (if installed), basically a temporary workaround until they fix this.

The update will probably land in 1 or 2 days.

**Comment by Pallas13** [comment]
Yes, but have erros of LD_PRELOAD.

**Comment by pythonlover02** [comment]
Edit:
It had been changed when running the compatibility layer inside of Steam but for whatever reason not for UMU(other launchers), i will see if i can add a workaround.

**Comment by Pallas13** [comment]
I understood, here, also the 'PROTON_USE_WINE3D' broken execution of game and of Wine/Proton. Not I know is that defined DVXK variables (I defined) or a bug of Proton-Sarek.

**Comment by Pallas13** [comment]
These are the variations of the DXVK that has been defined. The performance
Is poor with PROTON_USE_WINE3D.

**Comment by pythonlover02** [comment]
That its normal, WineD3D its the default wrapper shipped by Wine, its not terrible, but its not good by any means, worst performance and compatibility its expected. Not a bug just how things work.

**Comment by pythonlover02** [comment]
Anyway, an update to this, it seems like i cannot fix this as its something set by UMU, they probably have a really nice reason for doing this and they will probably fix this on the near future. For now, I will only recommend using Proton-Sarek within Steam, as UMU is still experimental.
