### ISSUE TITLE
Strange frame drop in the game "Path of Exile"

### ISSUE THREAD

**Issue by Pakrohk** [pythonlover02/Proton-Sarek#3]
# Compatibility Report
- Name of the game with compatibility issues: Path Of exile 
- Steam AppID of the game: 238960

## System Information
- GPU:  R9 M280x
- Video driver version: extra/mesa 1:24.2.3-1  
- Kernel version: Linux 6.6.53-x64v-xanmod1-1-lts
- Link to full system information report : [Gist](https://gist.github.com/Pakrohk/5b8be39f6d04035a9f32ab1f5f9b7375)
- Proton version: Sarek9-15

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-238960.log](https://github.com/user-attachments/files/17235327/steam-238960.log)
## Symptoms 
I tested this game on Windows and achieved between 45 to 69 frames per second, but on Linux, I can't get more than 25 FPS (occasionally jumping to 29-32 FPS for short moments). This is strange because the resolution has no effect on the frame rate.

I performed this test with a Ryzen 7600X processor under similar conditions. The issue isn't limited to Proton Sarek; I tested with all versions of Proton from 9.10 to 9.15. Interestingly, only in the Sarek version of Proton does the game crash in DX12 mode, while it runs fine in other versions. Strangely, this problem doesn't occur on the Steam Deck, where the game runs without any frame drops

**Comment by Pakrohk** [comment]
I am using Wayland (what we noticed with the help of the Protonge kids was that the system was working out of CPU)
I also test and announce with version 9.0.3.

**Comment by pythonlover02** [comment]
> I am using Wayland (what we noticed with the help of the Protonge kids was that the system was working out of CPU) I also test and announce with version 9.0.3.

In that case i cant do much, its a general problem that its repeated on Sarek, GE-Proton and Valve Proton Builds, and seeing that it works well on the Steam Deck it should be an OS/Kernel related issue. Good Luck with that and i recommend this Discords for more help:
https://discord.gg/linuxgaming
https://discord.gg/protondb-official-server-481706387278397440
