### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by captainarcee** [pythonlover02/Proton-Sarek#9]
Step 2 under Native Install instructions needs to be updated to read "Create a ~/.steam/root/compatibilitytools.d directory if it does not exist."

Steam at some point changed where it looks for such files and the documentation need to be updated to relect these changes. GEProton thankfully had the updated documentation and placing the Sarek files in ~/.steam/root/compatibilitytools.d fixed the issue of not seeing Sarek as an option in compatibility settings.

**Comment by pythonlover02** [comment]
Thanks for letting me now *:)*, it has been fixed on this [commit](https://github.com/pythonlover02/Proton-Sarek/commit/bc7f409f045a0c7d1e909bc693ededc913dd36ed)
